[package]
name = "GoatBot"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = {version="0.4.41", features=["serde"]}
poise = "0.6.1"
serde = "1.0.219"
serenity = "0.12.4"
sqlx = {version="0.8.6", features=["sqlite", "runtime-tokio", "chrono"]}
tokio = {version="1.45.1", features=["full"]}
